apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master1
  labels:
    name: spark-master1
  name: spark-master1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-master1
    spec:
      nodeSelector:
        dsaas-spark-master1: "true"
      containers:
      - name: spark-master1
        image: registry.secuiot/infra/spark:2.1.0-hadoop2.6_1
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
            - name: spark-data
              mountPath: /data
        name: spark-master1
        ports:
        - containerPort: 7077
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        command:
          - "/bin/bash"
          - "-c"
          - "--"
        args :
          - './start-master1.sh &
          /opt/spark/bin/spark-submit --class com.skinfosec.dsp.simple.SimpleMain /data/dsp-svc-simple* 19&
          /opt/spark/bin/spark-submit --class com.skinfosec.dsp.simple.SimpleMain /data/dsp-svc-simple* 30&
        while true ; do sleep 3600 ; done'
      volumes:
        - hostPath:
            path: /disk1/spark/data
          name: spark-data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master2
  labels:
    name: spark-master2
  name: spark-master2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-master2
    spec:
      nodeSelector:
        dsaas-spark-master2: "true"
      containers:
      - name: spark-master2
        image: registry.secuiot/infra/spark:2.1.0-hadoop2.6_1
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
            - name: spark-data
              mountPath: /data
        name: spark-master2
        ports:
        - containerPort: 7077
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        command:
          - "/bin/bash"
          - "-c"
          - "--"
        args :
          - './start-master2.sh &
          /opt/spark/bin/spark-submit --class com.skinfosec.dsp.simple.SimpleMain /data/dsp-svc-simple* 19&
          /opt/spark/bin/spark-submit --class com.skinfosec.dsp.simple.SimpleMain /data/dsp-svc-simple* 30&
        while true ; do sleep 3600 ; done'
      volumes:
        - hostPath:
            path: /disk1/spark/data
          name: spark-data
