apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dsp-infra-eureka
  labels:
    component: dsp-infra-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: dsp-infra-eureka
  template:
    metadata:
      labels:
        component: dsp-infra-eureka
    spec:
      hostAliases:
      - ip: "10.250.238.35"
        hostnames:
        - "registry.secuiot"
      containers:
      - name: dsp-infra-eureka
        image: registry.secuiot/test/dsp-infra-eureka:18.07.09.20.51-SNAPSHOT
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
        env:
        - name: JVM_OPTS
          value: "-Xms512M -Xmx1024M -XX:MetaspaceSize=192M -XX:MaxMetaspaceSize=1024m"
        ports:
        - containerPort: 8761
          name: http
      nodeSelector:
        apigw: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: dsp-infra-eureka-cs
  labels:
    component: dsp-infra-eureka
spec:
  selector:
    component: dsp-infra-eureka
  ports:
  - protocol: "TCP"
    port: 8761
    targetPort: 8761
    name: dsp-infra-eureka-8761
  type: ClusterIP
