apiVersion: v1
kind: Service
metadata:
  name: dsp-infra-hystrix-turbine-lb
  labels:
    component: dsp-infra-hystrix-turbine
spec:
  selector:
    component: dsp-infra-hystrix-turbine
  ports:
  - protocol: "TCP"
    port: 9990
    targetPort: 9990
  type: LoadBalancer
