apiVersion: v1
kind: Service
metadata:
  name: dsp-ui-management-cs
  labels:
    component: dsp-ui-management
spec:
  selector:
    component: dsp-ui-management
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    name: dsp-ui-management-8080
  type: ClusterIP
