apiVersion: v1
kind: Service
metadata:
  name: dsp-ui-management-lb
  labels:
    component: dsp-ui-management
spec:
  selector:
    component: dsp-ui-management
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888
  type: LoadBalancer
