apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dsp-svc-alarm-111111111
  labels:
    component: dsp-svc-alarm-111111111
spec:
  replicas: 1
  selector:
    matchLabels:
      component: dsp-svc-alarm-111111111
  template:
    metadata:
      labels:
        component: dsp-svc-alarm-111111111
    spec:
      hostAliases:
      - ip: "10.250.238.35"
        hostnames:
        - "registry.secuiot"
      containers:
      - name: dsp-svc-alarm-111111111
        image: registry.secuiot/test/dsp-svc-alarm-111111111:18.04.30.17.15-SNAPSHOT
        ports:
        - containerPort: 8081
          name: http
      nodeSelector:
        dsaas-analy: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: dsp-svc-alarm-111111111-cs
  labels:
    component: dsp-svc-alarm-111111111
spec:
  selector:
    component: dsp-svc-alarm-111111111
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
    name: dsp-svc-alarm-111111111-8081
  type: ClusterIP
