apiVersion: v1
kind: Service
metadata:
  name: dsp-svc-aggregator-cs
  labels:
    component: dsp-svc-aggregator
spec:
  selector:
    component: dsp-svc-aggregator
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
    name: dsp-aggregator-8081
  type: ClusterIP
